#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-isolated-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.17.0
  pipelineRef:
    name: isolated-build
  serviceAccountName: build-bot
  resources:
  - name: git-isolated
    resourceRef:
      name: git-isolated-main
  - name: git-obr
    resourceRef:
      name: git-obr-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
