FROM harbor.galasa.dev/docker_proxy_cache/library/httpd:alpine

ARG directory

RUN rm -v /usr/local/apache2/htdocs/*
COPY isolated/dockerfiles/httpdconf/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY ${directory}/target/isolated/ /usr/local/apache2/htdocs/